version: "3.8"

services:
  web:
    build: .
    restart: always
    networks:
      default: {}
      shared_net:
        aliases:
          - calculator

networks:
  shared_net:
    external: true
